[package]
name = "apollog"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
tokio = { version = "1.49.0", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.26.5"
tree-sitter-verilog = "1.0.3"
